# Generated by Django 2.0.9 on 2019-02-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190222_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='访客', max_length=50)),
                ('issue_time', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('img', models.TextField(default='banner5.jpg')),
            ],
            options={
                'verbose_name': '留言板管理',
                'verbose_name_plural': '留言板管理',
            },
        ),
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': '日记管理', 'verbose_name_plural': '日记管理'},
        ),
    ]
