# Generated by Django 2.0.9 on 2019-02-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190222_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='picture', verbose_name='图片')),
            ],
            options={
                'verbose_name': '照片管理',
                'verbose_name_plural': '照片管理',
            },
        ),
    ]
