# Generated by Django 2.0.9 on 2019-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190225_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
