# Generated by Django 2.0.9 on 2019-02-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190225_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='picture', verbose_name='图片'),
        ),
    ]
