# Generated by Django 2.0.9 on 2019-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190225_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discuss',
            options={'verbose_name': '文章评论管理', 'verbose_name_plural': '文章评论管理'},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article_img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='img',
            field=models.ImageField(upload_to='user_img', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='图片'),
        ),
    ]
