# Generated by Django 2.0.9 on 2019-02-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190225_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='img',
            new_name='image',
        ),
    ]
