# Generated by Django 2.0.9 on 2019-02-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190225_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.ImageField(upload_to='msg_img', verbose_name='图片'),
        ),
    ]
